import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable, map } from 'rxjs';
import {
  FeeText,
  League,
  LocalizationKey,
  LocalizedFeeText,
  Text,
} from 'src/app/common/types/league';

@Component({
  selector: 'app-leagues',
  templateUrl: './leagues.component.html',
  styleUrls: ['./leagues.component.sass'],
})
export class LeaguesComponent {
  constructor(private route: ActivatedRoute) {
    this.leagueId$ = this.route.params.pipe(
      map((params) => Number(params['id']))
    );
  }

  leagueId$: Observable<number> = new Observable<number>();

  onSeasonChange(season: any) {
    this.selectedSeason = season.target.value;
    console.log(this.selectedSeason);
  }

  league: League = {
    tabs: ['overview', 'table', 'matches', 'stats', 'transfers'],
    allAvailableSeasons: [
      '2023/2024',
      '2022/2023',
      '2021/2022',
      '2020/2021',
      '2019/2020',
      '2018/2019',
      '2017/2018',
      '2016/2017',
      '2015/2016',
      '2014/2015',
      '2013/2014',
      '2012/2013',
      '2011/2012',
      '2010/2011',
    ],
    details: {
      id: 47,
      type: 'league',
      name: 'Premier League',
      selectedSeason: '2023/2024',
      latestSeason: '2023/2024',
      shortName: 'Premier League',
      country: 'ENG',
      faqJSONLD: null,
      breadcrumbJSONLD: {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          {
            '@type': 'ListItem',
            position: 1,
            name: 'Home',
            item: 'https://www.fotmob.com',
          },
          {
            '@type': 'ListItem',
            position: 2,
            name: 'Premier League',
            item: 'https://www.fotmob.com/leagues/47/overview/premier-league',
          },
        ],
      },
    },
    seostr: 'premier-league',
    QAData: [],
    playoff: null,
    overview: {
      season: '2023/2024',
      selectedSeason: '2023/2024',
      table: [],
      topPlayers: {
        byRating: [
          {
            id: 675088,
            name: 'Rodri',
            rank: 1,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'ESP',
            cname: null,
            teamId: 8456,
            teamName: 'Manchester City',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 7.99,
          },
          {
            id: 292462,
            name: 'Mohamed Salah',
            rank: 2,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'EGY',
            cname: null,
            teamId: 8650,
            teamName: 'Liverpool',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 7.92,
          },
          {
            id: 493165,
            name: 'James Maddison',
            rank: 3,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'ENG',
            cname: null,
            teamId: 8586,
            teamName: 'Tottenham Hotspur',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 7.91,
          },
        ],
        byGoals: [
          {
            id: 737066,
            name: 'Erling Haaland',
            rank: 1,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'NOR',
            cname: null,
            teamId: 8456,
            teamName: 'Manchester City',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 14,
          },
          {
            id: 292462,
            name: 'Mohamed Salah',
            rank: 2,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'EGY',
            cname: null,
            teamId: 8650,
            teamName: 'Liverpool',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 14,
          },
          {
            id: 591734,
            name: 'Dominic Solanke',
            rank: 3,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'ENG',
            cname: null,
            teamId: 8678,
            teamName: 'Bournemouth',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 12,
          },
        ],
        byAssists: [
          {
            id: 292462,
            name: 'Mohamed Salah',
            rank: 1,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'EGY',
            cname: null,
            teamId: 8650,
            teamName: 'Liverpool',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 8,
          },
          {
            id: 540088,
            name: 'Ollie Watkins',
            rank: 2,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'ENG',
            cname: null,
            teamId: 10252,
            teamName: 'Aston Villa',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 8,
          },
          {
            id: 961995,
            name: 'Bukayo Saka',
            rank: 3,
            goals: null,
            assists: null,
            rating: null,
            positionId: null,
            ccode: 'ENG',
            cname: null,
            teamId: 9825,
            teamName: 'Arsenal',
            showRole: null,
            showCountryFlag: null,
            showTeamFlag: true,
            excludeFromRanking: false,
            value: 7,
          },
        ],
        seeAllUrl: 'stats',
      },
      hasTotw: true,
      leagueOverviewMatches: [],
      hasOngoingMatch: false,
    },
    transfers: {
      type: 'Transfers',
      data: [
        {
          contractExtension: false,
          fee: {
            feeText: FeeText.Fee,
            localizedFeeText: LocalizedFeeText.TransferFee,
            value: '€ 2.00m',
          },
          fromClub: 'Barca Atletic',
          fromClubId: 161774,
          marketValue: '€ 2.00m',
          name: 'S. Gnabry',
          onLoan: false,
          playerId: 30981,
          position: {
            key: 'ST',
            label: 'Midfielder',
          },
          toDate: new Date('2023-06-30T00:00:00Z'),
          toClub: 'FC Bayern München',
          toClubId: 6628,
          transferDate: new Date('2018-07-01T00:00:00Z'),
          transferText: [],
          transferType: {
            localizationKey: LocalizationKey.Contract,
            text: Text.Contract,
          },
          fromDate: new Date('2017-07-01T00:00:00Z'),
        },
        {
          contractExtension: false,
          fee: {
            feeText: FeeText.Fee,
            localizedFeeText: LocalizedFeeText.TransferFee,
            value: '€ 2.00m',
          },
          fromClub: 'Barca Atletic',
          fromClubId: 161774,
          marketValue: '€ 2.00m',
          name: 'S. Gnabry',
          onLoan: false,
          playerId: 30981,
          position: {
            key: 'ST',
            label: 'Midfielder',
          },
          toDate: new Date('2023-06-30T00:00:00Z'),
          toClub: 'FC Bayern München',
          toClubId: 6628,
          transferDate: new Date('2018-07-01T00:00:00Z'),
          transferText: [],
          transferType: {
            localizationKey: LocalizationKey.Contract,
            text: Text.Contract,
          },
          fromDate: new Date('2017-07-01T00:00:00Z'),
        },
        {
          contractExtension: false,
          fee: {
            feeText: FeeText.Fee,
            localizedFeeText: LocalizedFeeText.TransferFee,
            value: '€ 2.00m',
          },
          fromClub: 'Barca Atletic',
          fromClubId: 161774,
          marketValue: '€ 2.00m',
          name: 'S. Gnabry',
          onLoan: false,
          playerId: 30981,
          position: {
            key: 'ST',
            label: 'Midfielder',
          },
          toDate: new Date('2023-06-30T00:00:00Z'),
          toClub: 'FC Bayern München',
          toClubId: 6628,
          transferDate: new Date('2018-07-01T00:00:00Z'),
          transferText: [],
          transferType: {
            localizationKey: LocalizationKey.Contract,
            text: Text.Contract,
          },
          fromDate: new Date('2017-07-01T00:00:00Z'),
        },
        {
          contractExtension: false,
          fee: {
            feeText: FeeText.Fee,
            localizedFeeText: LocalizedFeeText.TransferFee,
            value: '€ 2.00m',
          },
          fromClub: 'Barca Atletic',
          fromClubId: 161774,
          marketValue: '€ 2.00m',
          name: 'S. Gnabry',
          onLoan: false,
          playerId: 30981,
          position: {
            key: 'ST',
            label: 'Midfielder',
          },
          toDate: new Date('2023-06-30T00:00:00Z'),
          toClub: 'FC Bayern München',
          toClubId: 6628,
          transferDate: new Date('2018-07-01T00:00:00Z'),
          transferText: [],
          transferType: {
            localizationKey: LocalizationKey.Contract,
            text: Text.Contract,
          },
          fromDate: new Date('2017-07-01T00:00:00Z'),
        },
      ],
    },
  };
  selectedSeason = `${this.league.details?.selectedSeason}`;
}
